name: Frequent Product Hunt Snapshot

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Fetch Product Hunt posts
        env:
          PH_TOKEN: ${{ secrets.PRODUCT_HUNT_TOKEN }}
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M')
          mkdir -p output
          node scripts/fetch_producthunt.js > output/posts-${TIMESTAMP}.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          publish_dir: ./output
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
